app:
  name: polaris
  namespace: metastore

image:
  repository: miguelrodas/polaris-polaris
  tag: "1.0"
  pullPolicy: IfNotPresent

replicaCount: 1

service:
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 8181
      targetPort: 8181
    - name: admin
      protocol: TCP
      port: 8182
      targetPort: 8182

resources:
  requests:
    memory: "128Mi"
    cpu: "250m"
  limits:
    memory: "256Mi"
    cpu: "500m"

awsAccessKeyId: "minioadmin"
awsSecretAccessKey: "minioadmin123"
awsRegion: "us-east-1"